# config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'sessions',
    registrations: 'registrations'
  }

  # Your other routes...

  # Add a route for checking the user's authentication status
  get '/auth_check', to: 'sessions#auth_check'

  # Public route for Farmer dashboard
  get 'farmer/dashboard' # Uncomment if needed

  # Authenticated user root route
  authenticated :user do
    root 'sessions#after_sign_in_path_for'
  end

  # Admin dashboard route
  get 'admin/dashboard', to: 'admin#dashboard', as: :admin_dashboard

  # Authenticated Buyer dashboard route (generated by Devise)
  authenticated :user do
    get 'buyer/dashboard', to: 'buyer#dashboard', as: :buyer_dashboard
  end

  # Resourceful routes for various entities
  resources :orders
  resources :products
  resources :categories
  resources :users
end
